import { chromium } from "/opt/node22/lib/node_modules/playwright/index.mjs";
const b = await chromium.launch();
const page = await b.newPage({ viewport:{width:1200,height:900} });
const errs=[]; page.on("pageerror",e=>errs.push(String(e)));
page.on("console",m=>{const t=m.text(); if(m.type()==="error"&&!t.includes("defaultProps"))errs.push(t);});
await page.goto("http://127.0.0.1:8899/build/index.html");
await page.waitForFunction(()=>window.__ready===true,null,{timeout:15000});
await page.waitForTimeout(400);
let fail=0; const check=(n,c,x="")=>{console.log((c?"PASS  ":"FAIL  ")+n+(c?"":"  "+x)); if(!c)fail++;};
const bar = page.locator('[role="status"]');
check("no runtime errors", errs.length===0, errs.join(" | "));
check("banner visible", await bar.isVisible());
check("banner says DEMO", (await bar.innerText()).includes("DEMO"));
check("banner names the unconfirmed figures", (await bar.innerText()).toLowerCase().includes("not yet confirmed"));
const box = await bar.boundingBox();
check("banner pinned to top", box && box.y === 0, JSON.stringify(box));
check("banner spans viewport", box && box.width >= 1190, JSON.stringify(box));
// It must not cover the booking sheet when that opens.
await page.locator("#book button").click(); await page.waitForTimeout(500);
const dlg = await page.locator('[role="dialog"]').boundingBox();
check("booking sheet still reachable over banner", !!dlg && dlg.height > 100, JSON.stringify(dlg));
await page.keyboard.press("Escape"); await page.waitForTimeout(400);
await bar.locator("button").click(); await page.waitForTimeout(200);
check("dismiss hides it", !(await bar.isVisible()));
await page.reload(); await page.waitForFunction(()=>window.__ready===true);
await page.waitForTimeout(400);
check("returns on reload (dismissal not persisted)", await page.locator('[role="status"]').isVisible());
await page.setViewportSize({width:390,height:844}); await page.waitForTimeout(300);
const sx = await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);
check("no horizontal overflow at 390px", sx<=1, "overflow "+sx);
console.log(fail?`\n${fail} FAILED`:"\nAll checks passed");
await b.close(); process.exit(fail?1:0);
